var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                       u                                                        ",
   "                                                                                ",
   "                     xxixx                                                      ",
   "                    xx!!!xx    yyyyy              yyyyyyyyyyyy                  ",
   "                    xx!!!xx             o o                                     ",
   "                    xx!!!xx                                      xx   |   xx    ",
   "                     xxvxx             yyyyy                      xx!!!!!xx     ",
   "                               o o                                 xx!!!xx      ",
   "  xx                                                                 xxx        ",
   "  x                           yyyyy                                             ",
   "  x               o                                                       yyyyy ",
   "  x          yyyy                 x                  x                    yyyyy ",
   "  x  @       y  y o               x       r          x                 t  yyyyy ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx               xxxxxxxxxx ",
   "                              x   x                  x               x          ",
   "                              x!!!x                  x!!!!!!!!!!!!!!!x          ",
   "                              x!!!x                  x!!!!!!!!!!!!!!!x          ",
   "                              xxxxx                  xxxxxxxxxxxxxxxxx          ",
   "                                                                                ",
   "                                                                                "],
["                                                                                                                           ",
 "                                                                                                                           ",
 "                                                                                                                           ",
 "                                                                                                                           ",
 "                                                                                                                           ",    
 "                                                                                                                           ",
 "                                                                                                              t            ",
 "                                                                                                          yyyyyyyyy        ",
 "                                                                                                                           ",
 "                                                          xx        xx                   xxxxx||xxxx                       ",
 "                                                          xxxxxxxxxxxx                   xx!!!!!!!xx                       ", 
 "                                                            o o o o o                    xx!!!!!!!xx                       ",
 "                                                            o o o o o     s              xx!!!!!!!xx                       ",
 "                                                        xx  o o o o o xi             yyyyxx!!!!!!!xx                       ",
 "                                                        xxxxxxxxxxxxxxxx                  xx!!!!!xx                        ",
 "                                                 yyyy                                       xxvxx                          ",
 "                                                                                                                           ",
 "                                                                      xx   xxxxx                                           ",
 "                                          yyyyyy   xx      xx         xx    xx                                             ",
 "                                  o                 xx    xx          xx  o xx     yyyyyyy                                 ",
 "                                                    xx    xx          xxx   xx                o o                          ",
 "                                 xxx                xx    xx          xx    xx                                             ",
 "                               xxxxxx               xx    xx          xx    xx              yyyyyyi                        ",
 "                      yy     xxxxxxxxxx             xx    xxxxxxxxxxxxxx    xx                                             ",
 "             @             xxxxxxxxxxxxxx           xx                     xxx         xx      u    xx                     ",
 "         xxxxxxxx         xxxxxxxxxxxxxxxx          xx          =           xx         xx           xx                     ",
 "         xxxxxxxx         xxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxx                      ",
 " !!!!!!!!xxxxxxxx!!!!|!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
 " !!!!!!!!xxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
 " !!!!!!!!xxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
 " !!!!!!!!xxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
 " !!!!!!!!xxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
 " !!!!!!!!xxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
 " !!!!!!!!xxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "                      xx                                                                                      ",
   "                      xx                                                                                      ",
   "                      xx                                                                                      ",
   "                      xx                   o        o        o                                                ",
   "                      xx                                                 o                                    ",
   "                      xx           xx      r             r       xxxxx                                        ",
   "                      xx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                      xx           xx                                    xxxx|xxxx                            ",
   "                      xx           xx                                    xx!!!!!xx                            ",
   "                      xx           xx                                    xx!!!!!xx    yyyyyyy                 ",
   "                      xx           xx                                    xx!!!!!xx                            ",
   "                     xx      t      xx                                   xxxxvxxxx                            ",
   "                     xx!!|!!yyy!!|!!xx                                                                        ",
   "                     xxxxxxxxxxxxxxxxx                                                         yyyyyyy        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                        xx      xx   yyyyyyyyy                ",
   "                                                                        xxx     xx                            ",
   "                                                                        xx      xx                            ",
   "                                              xx     xx                 xx      xx                            ",
   "                                 xx o o xx    xx     xx                 xx     xxx                            ",
   "                                 xx o o xx    xx     xx                 xx      xx                            ",
   "                                 xx     xx    xx     xx                 xx      xx                            ",
   "                                  xxxxxxx     xx     xx                 xx      xx                            ",
   "                                              xx     xxxxxxxxxxixxxxxxxxxxx     xx                            ",
   "                        s                     xx                                xx                            ",
   "                    yyyyyyyy                  xx                               xxx                            ",
   "          @                                   xx      o            o            xx                            ",
   "    xxxxxxxxxxxx                              xx            =            =      xx                            ",
   "    xxxxxxxxxxxx                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                                             ",
    "																											  ",
	"                                                                                                             ",
	"                                                                                                             ",
	"                                                                                                             ",
	"       xx        xx    xxxxx      xxx       xxx       xx                      xx  xxxxxx   xxxx         xx   ",
	"        xx      xx   xx     xx     xx       xx         xx                    xx     xx     xx xx        xx   ",
	"         xx    xx   xx       xx    xx       xx          xx                  xx      xx     xx  xx       xx   ",
	"          xx  xx   xx         xx   xx       xx           xx                xx       xx     xx   xx      xx   ",
	"            xx     xx         xx   xx       xx            xx      xx      xx        xx     xx    xx     xx   ",
	"            xx     xx         xx   xx       xx             xx     xx     xx         xx     xx     xx    xx   ",
	"            xx     xx         xx   xx       xx              xx    xx    xx          xx     xx      xx   xx   ",
	"            xx     xx         xx   xx       xx               xx   xx   xx           xx     xx       xx  xx   ",
	"            xx      xx       xx     xx     xx                 xx  xx  xx            xx     xx        xx xx   ",
	"            xx        xxxxxxx        xxxxxxx                   xx    xx          xxxxxxxx  xx         xxxx   ", 
	"                                                                                                             ",
	"                                                                                                             ",
	"                                                                                                             ",
	"    @                                                                                                        ",
	" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	" !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	" !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
